# Generated by Django 4.2.1 on 2023-05-11 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adoption', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='animal',
            old_name='user',
            new_name='added_by_user',
        ),
    ]
