# Generated by Django 4.2.1 on 2023-05-11 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adoption', '0002_rename_user_animal_added_by_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='image',
            field=models.ImageField(upload_to='uploads'),
        ),
    ]
