# Generated by Django 4.2.1 on 2023-05-12 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adoption', '0004_alter_animal_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='image',
            field=models.ImageField(upload_to='uploads'),
        ),
    ]
