# Generated by Django 4.2.1 on 2023-05-12 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adoption', '0005_alter_animal_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='age',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='animal',
            name='description',
            field=models.TextField(max_length=255),
        ),
    ]
