# Generated by Django 4.2.1 on 2023-05-18 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adoption', '0007_alter_animal_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='category',
            field=models.CharField(choices=[('CAT', 'CAT'), ('DOG', 'DOG'), ('HUMSTER', 'HUMSTER'), ('GUINEA PIG', 'GUINEA_PIG'), ('PARROT', 'PARROT'), ('OTHER', 'OTHER')], default='CAT', max_length=35),
        ),
    ]
