# Generated by Django 4.2.1 on 2023-05-19 06:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adoption', '0008_alter_animal_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animal',
            name='breed',
        ),
        migrations.AddField(
            model_name='animal',
            name='date',
            field=models.DateField(default=datetime.date.today, verbose_name='added'),
        ),
    ]
