# Generated by Django 4.2.1 on 2023-06-28 19:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('adoption', '0009_remove_animal_breed_animal_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='slug',
            field=models.SlugField(default=django.utils.timezone.now, max_length=250),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='animal',
            name='category',
            field=models.CharField(choices=[('CAT', 'CAT'), ('DOG', 'DOG'), ('HUMSTER', 'HUMSTER'), ('GUINEA PIG', 'GUINEA_PIG'), ('PARROT', 'PARROT'), ('OTHER', 'OTHER')], default='', max_length=35),
        ),
    ]
