# Generated by Django 4.2.1 on 2023-06-28 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adoption', '0010_animal_slug_alter_animal_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='slug',
            field=models.SlugField(max_length=255),
        ),
    ]
